language: node_js
before_script:
  - sleep 15
os:
  - linux
  - osx
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - iojs
services:
  - mongodb
env:
  - secure: a9T/G/aifA7YFzJuNGFRKUuejIcrDRYXpKEQVX9PMJ20KtNJ8/waO1Fy0Je1MHHWXAMBMAPkQo5cJElS56FiB0vJBpo70iClWBdBT3b9fxT6t3b3f9XOADjuVgyiEYY68SM3tSdEuix1M+BubRfKW+6tgbmI9fL2sFScY2z2kAg=
after_success: npm run codeclimate
